from tkinter import*
from tkinter import ttk
root = Tk()
mainmenu = Menu(root)
root.config(menu = mainmenu)
filemenu = Menu(mainmenu, tearoff=0)
filemenu.add_command(label = 'Открыть')
filemenu.add_command(label = 'Новый')
filemenu.add_command(label = 'Сохранить')
helpmenu = Menu(mainmenu, tearoff=0)
helpmenu.add_command(label = 'Помощь')
helpmenu2 = Menu(helpmenu, tearoff=0)
helpmenu2.add_command(label = 'Локальная отправка')
helpmenu2.add_command(label = 'Сообщение автора')
helpmenu.add_cascade(label = 'Помощь',menu = helpmenu2)
helpmenu2.add_command(label = 'О программе')
helpmenu.add_command(label = 'О программе')
mainmenu.add_cascade(label = 'Файл', menu = filemenu)
mainmenu.add_cascade(label = 'Помощь', menu = helpmenu)
root.mainloop()
